### ISSUE TITLE
4月1日限定で動作するようにして欲しい

### ISSUE THREAD

**Issue by naoaki011** [alfasado/mt-plugin-alpen#1]
とてもウザいので、4月1日のみ動作するようにしてください。
忘れたまま、翌年4月1日に表示されるのは可です。

**Comment by okayama** [comment]
外せばいいじゃないですかw

**Comment by 45shiki** [comment]
こんな楽しいものを4月1日に限定してしまうのはもったいないですww

**Comment by naoaki011** [comment]
見解の相違があって残念ですwww
